platform :ios, '15.0'

source 'https://github.com/CocoaPods/Specs.git'

project '/users/akonst17/Documents/OtterScaleiOS/OtterScaleiOS.xcodeproj'

use_frameworks!

target 'OtterScaleiOSExamples' do
  pod 'OtterScaleiOS', :path => '../'
  pod 'SwiftyStoreKit'
end
